# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 10:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_bootstrap3', '0014_translations_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap3carouselslidefolderplugin',
            name='folder',
            field=filer.fields.folder.FilerFolderField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.Folder', verbose_name='Folder'),
        ),
    ]
