# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 10:52
from __future__ import unicode_literals

import aldryn_bootstrap3.model_fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('filer', '0010_auto_20180414_2058'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aldryn_bootstrap3', '0015_auto_20190318_1044'),
    ]

    operations = [
        migrations.RenameModel(
            'Boostrap3AlertPlugin',
            'Bootstrap3AlertPlugin',
        ),
        migrations.RenameModel(
            'Boostrap3BlockquotePlugin',
            'Bootstrap3BlockquotePlugin',
        ),
        migrations.RenameModel(
            'Boostrap3ButtonPlugin',
            'Bootstrap3ButtonPlugin',
        ),
        migrations.RenameModel(
            'Boostrap3CitePlugin',
            'Bootstrap3CitePlugin',
        ),migrations.RenameModel(
            'Boostrap3IconPlugin',
            'Bootstrap3IconPlugin',
        ),
        migrations.RenameModel(
            'Boostrap3ImagePlugin',
            'Bootstrap3ImagePlugin',
        ),
        migrations.RenameModel(
            'Boostrap3JumbotronPlugin',
            'Bootstrap3JumbotronPlugin',
        ),
        migrations.RenameModel(
            'Boostrap3LabelPlugin',
            'Bootstrap3LabelPlugin',
        ),
        migrations.RenameModel(
            'Boostrap3PanelBodyPlugin',
            'Bootstrap3PanelBodyPlugin',
        ),
        migrations.RenameModel(
            'Boostrap3PanelFooterPlugin',
            'Bootstrap3PanelFooterPlugin',
        ),
        migrations.RenameModel(
            'Boostrap3PanelHeadingPlugin',
            'Bootstrap3PanelHeadingPlugin',
        ),
        migrations.RenameModel(
            'Boostrap3PanelPlugin',
            'Bootstrap3PanelPlugin',
        ),
        migrations.RenameModel(
            'Boostrap3SpacerPlugin',
            'Bootstrap3SpacerPlugin',
        ),
        migrations.RenameModel(
            'Boostrap3WellPlugin',
            'Bootstrap3WellPlugin',
        ),
    ]
